### ISSUE TITLE
ModuleNotFoundError: No module named 'datahouneed'

### ISSUE THREAD

**Issue by yyzk0618** [Event-AHU/VehicleMAE#4]
![image](https://github.com/user-attachments/assets/6c78bd5a-d215-4957-8955-c807c7362483)
I am encountering a ModuleNotFoundError when trying to run the main.py script in the VehicleMAE project. The error message indicates that the module datahouneed cannot be found.

Error Message:
(vehiclemae) yaozekai@gdd:~/VehicleMAE-main$ CUDA_VISIBLE_DEVICES=0 python main.py
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    from models.clipmodel import ClipBaseModel, build_clip
  File "/home/yaozekai/VehicleMAE-main/models/clipmodel.py", line 4, in <module>
    from datahouneed import HICO_INTERACTIONS
ModuleNotFoundError: No module named 'datahouneed'
Steps Taken:
Verified the spelling of the module name.
Checked the project directory for any similar module names.
Ensured that my Python environment is correctly set up.
Request for Help:
Is datahouneed a typo, or is it a module that needs to be installed separately?
If it is a custom module, could you provide information on where to find it or how to install it?
Any other suggestions to resolve this issue?
Thank you for your assistance.

**Comment by Vehicle-AHU** [comment]
You can download this file from our public dataset link, named ‘text.py’.
